### ISSUE TITLE
How can I root

### ISSUE THREAD

**Issue by 55ahmedsalah** [MisterZtr/PixelOS_gsi#101]
Hello man, thank you so much for the amazing GSI

Wanted to ask about rooting:

My phone is Infinix Note 11 X663 and installed this GSI via DSU to try it and maybe make it my default OS if all goes well.

Had problems with Bluetooth and no audio during calls, but was able to fix them after tinkering with the settings.

But I want to root it, can you please tell me the steps.

**Comment by imbroglius** [comment]
Read about Magisk

**Comment by VTVishwanath** [comment]
https://www.youtube.com/watch?v=6SpCrBaWV44
https://www.youtube.com/watch?v=XlnTu7DgR0Y
https://www.reddit.com/r/androidroot/comments/1bukl33/how_to_root_infinix_x6831/
https://www.google.com/search?q=root+infinix+phone&rlz=1C1CHBF_enIN1050IN1050&ie=UTF-8

**Comment by 55ahmedsalah** [comment]
This does not answer my question

My phone is rooted but the GSI on the DSU is not

I want to root the GSI image not the stock XOS

**Comment by VTVishwanath** [comment]
None of the GSI or Custom ROMS by default rooted. For that you need to flash Magisk Manager from your custom Recovery like TWRP or OrangeFox after installing GSI or flashing the ROM.

Link: https://magiskmanager.com/
