### ISSUE TITLE
Cannot install apk in latest beta build

### ISSUE THREAD

**Issue by Giocraft125** [MisterZtr/PixelOS_gsi#11]
If I try to install apk in the latest beta it tells me that the device is incompatible. (Play store installs them without a problem)

**Comment by MisterZtr** [comment]
What does it look like? I had no problem installing the apk files

**Comment by Amanse** [comment]
play store automatically selects the apk for the device but if u download manually u may need another target API or architecture, can you tell the apk name(full name of the downloaded file if u used apkmirror) and your device's SoC?

**Comment by Giocraft125** [comment]
> play store automatically selects the apk for the device but if u download manually u may need another target API or architecture, can you tell the apk name(full name of the downloaded file if u used apkmirror) and your device's SoC?

I have a Dimensity 8020 (Motorola Edge 40) and when downloading apk from fdroid it doesn't install them

**Comment by Amanse** [comment]
which app is it? if it's on both fdroid and play store there are chances the play store app is different(like the case with telegram/session) and the fdroid version is FOSS version and may have not been compiled for your architecture. I can confirm if you tell me the app name

**Comment by Giocraft125** [comment]
Well, pretty much every application, when I click install it doesn't install it but if I download the apk separately it tells me it's not compatible.
But for instance, I tried "file manager utils", "lemuroid" and "data backup".
Thanks.

**Comment by Amanse** [comment]
interesting... lemuroid seems to have minimum API correct but play services restrictions might differ depending on their roll out, somsone on reddit suggests you might be able to install it by using adb using `adb install --bypass-low-target-sdk-block name_of_package.apk`. Also you can get the exact error if you use `adb install name.apk` i would suggest running that first. I have installed a few apps from fdroid and they work like stealth and newpipe but they are updated much more frequently than those 3

edit: lemuroid installs for me from fdroid

**Comment by Giocraft125** [comment]
Ok, thank you, I'll try in the afternoon.
