### ISSUE TITLE
Please add unisoc sc9863a support

### ISSUE THREAD

**Issue by Skorpion96** [MisterZtr/PixelOS_gsi#13]
I tried this gsi (latest android 14 release) on unisoc sc9863a vndk28, it stucks on bootanimation, so i suppose that with unisoc patches it may boot

**Comment by IverCoder** [comment]
This is a TrebleDroid matter, can you try opening an issue on [their repo](https://github.com/TrebleDroid/treble_experimentations) or asking on their [Telegram group](https://t.me/phhtreble)?

**Comment by Skorpion96** [comment]
i guess they won't support my kernel anyway, too old, 4.4.147+, you can close the issue. or i will

**Comment by IverCoder** [comment]
> i guess they won't support my kernel anyway, too old, 4.4.147+, you can close the issue. or i will

You can still try, after all their main goal is to extend the lifetime of devices. They support even way older kernels, I used to be fairly active in that group and they even tackle issues on devices with v3 kernels.
