### ISSUE TITLE
I've had 2 phones with QC snapdragon chips with SMS issues

### ISSUE THREAD

**Issue by SavedByLight** [MisterZtr/PixelOS_gsi#15]
I had a Samsung Galaxy S20 Fe and a Moto G53 5g, both snapdragon, now the issue seems to be with f2a SMS, my friends can text me sometimes but I get no verification codes, I've messed with the network settings *#*#4636#*#* and I've tried ims which just crashes my settings menu every 5 minutes, any ideas?

**Comment by IverCoder** [comment]
As for your Galaxy S20 FE, it's a common issue for Samsung firmwares built around August 2023 and later. Can you try [this Magisk module](https://github.com/IverCoder/a03nnxx-ril-rollback) and see if it gets fixed?

**Comment by SavedByLight** [comment]
Issue solved with PHH new Floss IMS

**Comment by SavedByLight** [comment]
> Issue solved with PHH new Floss IMS
