### ISSUE TITLE
Proximity sensor 

### ISSUE THREAD

**Issue by dp-28AKM** [MisterZtr/PixelOS_gsi#17]
After make a call when phone near to head or ear it should turn off display light but ,it is not working I reset my device 2 times but not working in previous I used pixels experience plus then I am using this pixelOS  so kindly check this ..

**Comment by dp-28AKM** [comment]
When I was flashing this pixelOS then current time my device working on pixel experience plus which is also flashed with odin 
Then when I flash this pixelOS with odin I m shocked no data loss all data are still there and it was like update for pixel experience plus 
It just upgraded not changed to pixelOS like old things should remove but in my case all data are kept in it it save my lot of time but I am curious about sensor while calling my display light kept on while close to head or ear

**Comment by IverCoder** [comment]
It sounds like you have a Samsung device. Try going to `Settings > Phh Treble Settings > Samsung features` and then enable `Enable extra sensors`.

If that does not work, reformat data because dirty flashing across different ROMs will cause a lot of issues.

**Comment by dp-28AKM** [comment]
I try these thing and I am watching and observing Android 14 have bugs I try pixelOS,DERPFEST,aosp,crdorid,which all are Android 14 and not working with proximity sensor in Samsung a127f I don't know about others device but in my device not working,but android 13 work very well in pixel experience plus only boot logo showing in bottom corner which kind of bug I think 🤔 
But thanks for you information I try more then once
