### ISSUE TITLE
Unable to send an SMS

### ISSUE THREAD

**Issue by drmronthemoon** [MisterZtr/PixelOS_gsi#18]
Hey,
I'm willing to share with you this issue due to the fact that I can't send sms with your GSI after testing on my phones.
When I send an SMS I get error 0.

My devices:
Samsung Galaxy A23
Samsung Galaxy S9

Thanks!

**Comment by MisterZtr** [comment]
Try in " *#*#4636#*#* ", in the item "SMSC" write the number of sms center of your operator, and update it there. This helped on Xiaomi devices with mtk processors

**Comment by drmronthemoon** [comment]
Thank you for your response.
It helped!
