### ISSUE TITLE
Trebledroid Update

### ISSUE THREAD

**Issue by SavedByLight** [MisterZtr/PixelOS_gsi#20]
TD has just released a new IMS feature, it has fixed some of my connection issues, could you update this GSI so it includes the new IMS feature

**Comment by MisterZtr** [comment]
For the next build, need to wait for the PixelOS source code merged with Android 14 qpr1 to be ready

**Comment by SavedByLight** [comment]
Okay, it's not the latest Android update that's needed it's the latest trebledroid, phh added a new part for Floss IMS
