### ISSUE TITLE
SMS not sending

### ISSUE THREAD

**Issue by faraimartin** [MisterZtr/PixelOS_gsi#21]
Text messaging keeps throwing up error0 when trying to send SMS despite having unlimited messages. SMSC number is correct but does not appear on the radio info page.

**Comment by faraimartin** [comment]
Please note this is on the Note 20 Ultra 5g

**Comment by MisterZtr** [comment]
Duplicate https://github.com/MisterZtr/PixelOS_gsi/issues/18
