### ISSUE TITLE
VNDKLITE Request

### ISSUE THREAD

**Issue by aarslan007** [MisterZtr/PixelOS_gsi#24]
It'd be awesome if you could please add a VNDKLITE version of this GSI. Thanks.

**Comment by MisterZtr** [comment]
I think it doesn't make sense to support vndk lite builds. My past Meizu X8 with vndk lite 30 can't launch anything above android 12

**Comment by aarslan007** [comment]
That's not true for all phones. My Infinix Note 10 Pro has decent specs and runs AOSP 14 by Ponces just fine. So, VNDKLITE is worth it for many users.

**Comment by MisterZtr** [comment]
Test this build
[PixelOS_treble_arm64_bN-vndklite-test-14.0-20240130.img.xz](https://sourceforge.net/projects/misterztr-gsi/files/PixelOS/Android%2014/Tests/PixelOS_treble_arm64_bN-vndklite-test-14.0-20240130.img.xz/download)

**Comment by aarslan007** [comment]
Thanks. I'm currently testing a build by Ponces. Will try this as soon as I get the chance.

**Comment by MisterZtr** [comment]
I've added vndk lite builds to the latest release on github

**Comment by aarslan007** [comment]
Awesome! Thank you so much!😃
