### ISSUE TITLE
Netfilx Widevine L3

### ISSUE THREAD

**Issue by jpdakwind** [MisterZtr/PixelOS_gsi#28]
I Flash 0130 version but Netfilx Widevine is L3

This is Pixel experience (Andriod 13)
![9A14C2C3-DCCD-4117-B9B7-A2692E3AF1E3](https://github.com/MisterZtr/PixelOS_gsi/assets/93638761/18531879-4e65-4ec7-b601-489b6a3c394a)

This is Pixel OS (Android14)
![S__23568393](https://github.com/MisterZtr/PixelOS_gsi/assets/93638761/bdb71661-3f89-4c67-8971-39f04131401e)

**Comment by MisterZtr** [comment]
I don't use netflix, so I can't say anything about it
