### ISSUE TITLE
Random reboot and lockscreen auto rotation on large display

### ISSUE THREAD

**Issue by ankan2008** [MisterZtr/PixelOS_gsi#29]
After every 5 to 6 minutes, the device gets a soft reboot. This is a known bug and ponces' aosp gsis have got a fix to it,so plz implement a fix to this and release a new update.
Just love this gsi. Moreover, I use this gsi on a tablet, so plz enable lockscreen auto rotation

**Comment by MisterZtr** [comment]
Check the new build
