### ISSUE TITLE
Broken fingerptint (Galaxy A53 5G)

### ISSUE THREAD

**Issue by ost-sys** [MisterZtr/PixelOS_gsi#31]
In general, the fingerprint location is shown correctly and even attempts to register it. However, registration does not occur and the area does not light up properly.

https://github.com/MisterZtr/PixelOS_gsi/assets/66862161/e84418e0-c291-4d35-921e-8be86b29b66f

https://github.com/MisterZtr/PixelOS_gsi/assets/66862161/ad05f329-3ca1-427f-85ea-b0001f12ff7e

![Screenshot_20240302-170241_Pixel Launcher](https://github.com/MisterZtr/PixelOS_gsi/assets/66862161/741e71ba-6d14-4478-a9f4-e2e9be06db83)

**Comment by garryfieldd** [comment]
I have the same problem, hopefully it will be fixed in next release

**Comment by MisterZtr** [comment]
I can't fix bugs on individual devices. Contact users who are using this smartphone
