### ISSUE TITLE
Recover a backup

### ISSUE THREAD

**Issue by mytja** [MisterZtr/PixelOS_gsi#32]
Greetings,

thanks for this awesome project. I've tried it and I'm really liking it, apart from one issue.

I can't seem to get online backup recovery working (restore from backup saved in my Google Account). I get such an option offered twice whilst in setup, but when I click that I want to restore it from a backup and sign into my Google Account, the page where I select which backup to restore from doesn't appear as it does on other GSIs.

I've tried factory resetting the GSI twice and reflashing the system image twice and nothing changed. I am able to complete the initial setup, but the restore from backup option isn't displayed anywhere.

I haven't yet tried the newest build to see if it's fixed, but I've tried v2024.02.18.

I don't know if this is unique to my device (Samsung A53 5G; A536B; Exynos variant), so please let me know if I'm missing something here.

Thank you so much

**Comment by MisterZtr** [comment]
Yes, I see that possibility to make backup and restore it has stopped works too

**Comment by zefrs** [comment]
+1, same issue with me.

**Comment by MisterZtr** [comment]
This problem is not present in latest build
