### ISSUE TITLE
samsung S23 ULTRA Stock in bootloop,logo is small,can any one help

### ISSUE THREAD

**Issue by christiancui** [MisterZtr/PixelOS_gsi#36]
i flash latest gsi rom by twrp fastboot today,but it doesn't work,still stock in bootloop.what's wrong with me?

**Comment by ivanushka123amongus** [comment]
Try to flash with DynaPatch from SD, or OTG. When i tried to flash through the fastboot mine don't start too

**Comment by MisterZtr** [comment]
In the next update, I plan to enable forced adb, and device will need to be correctly detected
And if make a boot-logo of the right size for your screen resolution, then it totally break on HD screens

**Comment by ivanushka123amongus** [comment]
> And if make a boot-logo of the right size for your screen resolution, then it totally break on HD screens
Can you make it like on beta versions, it was greather

**Comment by Meralchen** [comment]
chris you found a fix for the not booting problem?
