### ISSUE TITLE
Antenna Abnormally Heats up too much when in use

### ISSUE THREAD

**Issue by Mizumo-prjkt** [MisterZtr/PixelOS_gsi#38]
Device: Samsung Galaxy A12s
Chipset: Exynos 850

Explaination:
When using the Wifi + Bluetooth, because i like to listen to yt music, it heats up too much, turning it off, cools it

The concerning thing is that the Antenna is hot on touch, like real hot than the rest of GSI, and its not commonly present on Beta for A14

For now im ditching the PixelOS GSI atm until a new builds are up, while this is just a point jic when someone has this issue, should probably say they have the same thing

**Comment by MisterZtr** [comment]
I can't fix bugs on individual devices. Contact users who are using this smartphone
