### ISSUE TITLE
docs: `generate.sh` not found

### ISSUE THREAD

**Issue by aquariuslt** [MisterZtr/PixelOS_gsi#4]
when follow README.md steps

after repo sync and clone repo and copy to `device/phh/treble`
``` 
bash generate.sh .
```

could not locate `generate.sh`

**Comment by MisterZtr** [comment]
generate.sh is located in "device/phh/treble"

**Comment by aquariuslt** [comment]
after search all `manifest.xml`, no repo will clone to `device/phh/treble`
