### ISSUE TITLE
Volume Control Not Working (Immediate Max/Mute & Static at Max Volume)

### ISSUE THREAD

**Issue by refurbishing** [MisterZtr/PixelOS_gsi#41]
My SM-A037M has some volume issues. When I press the volume up button, it jumps straight to max volume. And if I press volume down, it goes straight to silent, of course i have tried all PHH Treble audio related settings (ex: Use alternative audio policy) they don't do anything that solves this problem, and when i have max volume you can hear kinda of a static sound going from the speakers.

**Comment by MisterZtr** [comment]
Try this module
[Volume+step+control+29.zip](https://github.com/MisterZtr/PixelOS_gsi/files/14922800/Volume%2Bstep%2Bcontrol%2B29.zip)

**Comment by refurbishing** [comment]
> Try this module [Volume+step+control+29.zip](https://github.com/MisterZtr/PixelOS_gsi/files/14922800/Volume%2Bstep%2Bcontrol%2B29.zip)

didn't work

**Comment by MisterZtr** [comment]
I can't fix bugs on individual devices. Contact users who are using this smartphone
