### ISSUE TITLE
Galaxy Tab A9+ Automatic Brightness broken

### ISSUE THREAD

**Issue by UltraHQ** [MisterZtr/PixelOS_gsi#47]
On SM-X210 (Galaxy Tab A9+) automatic brightness is not working.
No option in the PHH Treble settings fixes it.

**Comment by MisterZtr** [comment]
The auto-brightness function depends on treble overlay for your device

**Comment by UltraHQ** [comment]
> The auto-brightness function depends on treble overlay for your device

I was about to make an overlay for the device. However, vendor and product have almost no files at all. Product only has powerprofile, which has no reference to brightness at all.
I'm not sure if an overlay is possible.

**Comment by SiCole180421** [comment]
> > The auto-brightness function depends on treble overlay for your device
> 
> I was about to make an overlay for the device. However, vendor and product have almost no files at all. Product only has powerprofile, which has no reference to brightness at all. I'm not sure if an overlay is possible.

File needed is in stock framework res apk in system/framework
