### ISSUE TITLE
Playstore device not certified 

### ISSUE THREAD

**Issue by sumeet4evr** [MisterZtr/PixelOS_gsi#48]
After clearing cache and data,still shows error. Magisk modules playintegrity installed, still shows error. Device Samsung F235g

**Comment by MisterZtr** [comment]
Is it that notifications you're getting about this?

**Comment by sumeet4evr** [comment]
Hi,

Thanks for the rom, CTS profile mismatch, using Gsi build on SM-E236B.

**Comment by sumeet4evr** [comment]
Hi,

Everything is working fine except banking apps, CTS profile mismatch.
Kindly help. Also lsposed not working.

**Comment by sumeet4evr** [comment]
Hi

How to enable
Certfied prop overlay ROM app disabled. Kindly help.

**Comment by sumeet4evr** [comment]
Hello MrZtr,

Thank you for awesome GSI, please let me know if we are getting latest
edition in July.


Thanks
Sumeet Sharma

**Comment by sumeet4evr** [comment]
Hi,

If possible please add live wallpapers.

Thanks
Sumeet Sharma

**Comment by sumeet4evr** [comment]
Hi,

Are we getting an update for PixelOS.

Thanks
Sumeet Sharma

**Comment by sumeet4evr** [comment]
Hi Mrztr,

Awesome ROM, except Volte is not working, Radio info keeps changing to
disable. Any suggestions.

Thanks
Sumeet Sharma

**Comment by sumeet4evr** [comment]
Hi,

Thanks for awesome gsi.

Sumeet Sharma
