### ISSUE TITLE
lunch treble_arm64_bvN-userdebug error

### ISSUE THREAD

**Issue by lingchenma** [MisterZtr/PixelOS_gsi#53]
13 branches
binghuang@binghuang-virtual-machine:~/PixelOS$ lunch treble_arm64_bvN-userdebug
In file included from build/make/core/config.mk:353:
In file included from build/make/core/envsetup.mk:352:
In file included from build/make/core/product_config.mk:237:
device/phh/treble/treble_arm64_bvN.mk:7: error:  device/phh/treble/pixel.mk does not exist..
04:29:51 dumpvars failed with: exit status 1
In file included from build/make/core/config.mk:353:
In file included from build/make/core/envsetup.mk:352:
In file included from build/make/core/product_config.mk:237:
device/phh/treble/treble_arm64_bvN.mk:7: error:  device/phh/treble/pixel.mk does not exist..
04:29:53 dumpvars failed with: exit status 1

**Comment by MisterZtr** [comment]
pixel.mk should be placed in the /device/phh/treble folder by yourself
