### ISSUE TITLE
Playstore apps crashing

### ISSUE THREAD

**Issue by SiCole180421** [MisterZtr/PixelOS_gsi#55]
Using Galaxy S24 Ultra on latest build on pling.
YouTube and Facebook apps are crashing on launch, logcat reader complains about window manager for both apps. Could be more but these 2 I use the most. Will report back if I notice any more apps

**Comment by MisterZtr** [comment]
I don't post my builds on pling. Also, on the latest beta, I have all of these apps working fine for me

**Comment by SiCole180421** [comment]
> I don't post my builds on pling. Also, on the latest beta, I have all of these apps working fine for me

Aah sorry, I meant sourceforge.. 

I'm using KSU and zygisk next reports zygote is crashing a whole lot and if I type zygote in logcat, it's everywhere including those apps I mentioned. Wondering now if it's a GKI issue or KSU issue. Will flash it again but with magisk and stock s24 ultra boot img
