### ISSUE TITLE
No incall audio

### ISSUE THREAD

**Issue by SiCole180421** [MisterZtr/PixelOS_gsi#56]
Incall audio not working on latest PixelOS QPR2 beta 
S24 Ultra SM-928B 

Also when call is made, proximity sensor isn't working to make screen turn off 

EDIT.. incall audio works on latest AOSP 14 GSI

**Comment by DocMAX** [comment]
Same here. Device Jelly Star.

**Comment by DocMAX** [comment]
Fixed it myself by enabling "Disable "Voice Call In" route" in Phh Treble Settings lol
