### ISSUE TITLE
Kernel 4.19 not booting may Update

### ISSUE THREAD

**Issue by Meralchen** [MisterZtr/PixelOS_gsi#57]
My S20FE is not booting in the May version of Andrew´s Pixel OS 
does Someone have found a fix for this.
Yes, i know that Google changed AOSP and booting on some devices can´t be possible.
But, i have hope that it works because in the changelog it said that there was fixes for kernels and something else so that older devices still can boot. 

Best regards
Melih Adalet

**Comment by MisterZtr** [comment]
Kernel 4.19 isn't that old yet. Fixes were for 4.14 and older

**Comment by nickpapoutsis** [comment]
On a Teclast T40s device with kernel 4.19 I had bootloops with latest Elixir 13/14 GSI but PixelOS worked fine (minus Bluetooth)

**Comment by Meralchen** [comment]
nickpapoutsis what kernel exactly 
like i have 4.19.87-gaab7192739b3-dirty (lineage21kernel)
maybe you have a newer version of that kernel 
or it maybe happening because of the exynos processor
i tried Elixir 14 too and had bootloops too

**Comment by Meralchen** [comment]
YESSSSS MATES i got it fixing
i always tried to flash it with TWRP but you need to flash the gsi with Fastboot

here the commands i used mates


fastboot erase system

fastboot flash system system.img

fastboot -w

fastboot reboot


nick it will probably work with Elixir too so if you want Elixir go for it

**Comment by Meralchen** [comment]
ehem Andrew is it normal for the May version to take so long to load bc since i flashed the gsi its only showing the google logo and is sometimes restarting

**Comment by MisterZtr** [comment]
> ehem Andrew is it normal for the May version to take so long to load bc since i flashed the gsi its only showing the google logo and is sometimes restarting

Get logcat
adb logcat >logcat.log
And I'd recommend you to flash data through recovery instead of doing fastboot -w

**Comment by Meralchen** [comment]
Just tried this gsi on an POCO X3 PRO and it worked fine i don´t know why its not working on the s20 fe also tried adb logcat and its sayin /system/bin/sh: logcat:  inaccessible or not found

also just sayin maybe it helps since you released the qpr 2 builds it didn´t boot too

just realised that my kernel is not supporting qpr2 a14 builds
so i might try kernel upstreaming

**Comment by nickpapoutsis** [comment]
> nickpapoutsis what kernel exactly like i have 4.19.87-gaab7192739b3-dirty maybe you have a newer version of that kernel or it maybe happening because of the exynos processor i tried Elixir 14 too and had bootloops too

My device has an MT8183

C:\adb>adb shell cat /proc/version
Linux version 4.19.191 (nobody@android-build) (Android (6443078 based on r383902) clang version 11.0.1 (https://android.googlesource.com/toolchain/llvm-project b397f81060ce6d701042b782172ed13bee898b79), LLD 11.0.1 (/buildbot/tmp/tmp6_m7QH b397f81060ce6d701042b782172ed13bee898b79)) #1 SMP PREEMPT Thu Jun 1 23:55:30 CST 2023

**Comment by noahhhi** [comment]
Got same issue on Galaxy Tab S7 plus

**Comment by Meralchen** [comment]
Mates i believe i found a fix,
i just need to test it.

Its a Kernel Upstream "https://github.com/maosith/msm-4.19-meow/releases".
i hope it works

**Comment by Meralchen** [comment]
mates it works you just need to upstream the kernel sadly the meow kernel isn't availiable on the exynos version yet but it will.

How do i come to the conclusion that you need to upstream the kernel?
on the s20 fe page of xda is a lineage 21 version with this kernel:
4.19.87-gaab7192739b3-dirtyand its compatible with qpr 2 (the lineage version is litteraly qpr2)

the normal stock rom has this kernel 4.19.87-27231340 which is not compatible with qpr 2 a14 i think. to support my argument: the lineage version has a custom kernel (4.19.87-gaab7192739b3-dirty) and it also boots in qpr2.

if you have questions ask them i will try to answer

Best regards
Adalet
