### ISSUE TITLE
bootanimation for tablet

### ISSUE THREAD

**Issue by brownursidaeR** [MisterZtr/PixelOS_gsi#61]
bootanimation on tablet device is not full width, hope can be fixed~

**Comment by MisterZtr** [comment]
If set bootanimation resolution higher than 720p, then on screens with less resolution, it will be like this
<img src=https://github.com/MisterZtr/PixelOS_gsi/assets/87061244/9d584313-fc4e-4f55-91b6-c6cec4843eae alt="drawing" width="200"/>

**Comment by MisterZtr** [comment]
I can only discount butanimation other screen sizes, for manual replacement in "/system/product/media"
[bootanimation_1080.zip](https://github.com/MisterZtr/PixelOS_gsi/files/15366704/bootanimation_1080.zip)
[bootanimation_1440.zip](https://github.com/MisterZtr/PixelOS_gsi/files/15366705/bootanimation_1440.zip)
