### ISSUE TITLE
Highlighting Some bugs on Samsung galaxy A23 and Tab A8

### ISSUE THREAD

**Issue by monsiu** [MisterZtr/PixelOS_gsi#64]
Hey the rom is awesome so i will help by highlighting bugs i may find. I have the OS on both a tablet(samsung tab a8 2021 SM-x200) and a phone (Samsung Galaxy A23 4G). I will mention when an issue is seen on both devices or one. Note that the phone is the only one with a sim card slot.

1: During setup, Google gives an option of copying apps and data but when the option pops up and i click "next" it loads a bit and skips it altogether. It goes to the option where it asks me to allow scanning,  Even in the 'Finish Device Setup' page that is usually seen in the notification panel after the setup does not allow me to copy and just skips it. Seen in both devices, tab and samsung. Attatched bug report for Samsung A23 after the setup and after continuing setup after the first setup(clicked in notification panel). 

[bugreport(1)-a23nsxx-AP1A.240505.005.B1-2024-05-22-10-26-47.zip](https://github.com/MisterZtr/PixelOS_gsi/files/15399715/bugreport.1.-a23nsxx-AP1A.240505.005.B1-2024-05-22-10-26-47.zip)

2: Messages not arriving, I have network bars but messages are not arriving. Asked for an OTP from two apps and its not showing me the message. Could it be linked to the sim issue [this person had](https://github.com/MisterZtr/PixelOS_gsi/issues/25)? But now in my case i can send texts but am not receiving any. Two different apps, so its not server issues on their end. I have no clue how to put logs here lol. Also in that light if you check the other issue i mentioned above, add that sim takes a bit to be detected.

3: Seems to be an issue with how the GSI handles SD cards. When choosing to format as internal Storage it gets stuck and at 49 percent just gives up. [Someone has brought up sd card issues](https://github.com/MisterZtr/PixelOS_gsi/issues/25) so maybe its linked to this case. When it panics it somehow allows me to detect the card in a drop down and i can click the SD card and format as portable storage and migrate data. Did it work, i honestly do not know since its supposed to let me migrate data right before quitting right? Anyway here are screenshots. when i go ahead to format as portable it gets stuck at 20 percent then says done but does not say done when i format as internal. Its a 2gb card and the tab am seeing it reflected so it works i guess. You can see the change in the screenshots that reflects an increase suitable for a 2gb card. Anyway here are logs taken after formatting as internal and portable. This issue is a problem in the Samsung phone A23 alone. Tab works perfectly and even asks me to migrate data.

[bugreport(3)-a23nsxx-AP1A.240505.005.B1-2024-05-22-09-31-25.zip](https://github.com/MisterZtr/PixelOS_gsi/files/15399765/bugreport.3.-a23nsxx-AP1A.240505.005.B1-2024-05-22-09-31-25.zip)

4: Mobile data connection is a bit spotty. Here is logs.
[bugreport(4)-a23nsxx-AP1A.240505.005.B1-2024-05-22-09-40-33.zip](https://github.com/MisterZtr/PixelOS_gsi/files/15399964/bugreport.4.-a23nsxx-AP1A.240505.005.B1-2024-05-22-09-40-33.zip)

5: Calls using the second sim goes through but can not hear the other person talking. Seems like a long lasting issue. Here is logs after making a call using my second sim. Sim one is perfect but noticed the front camera does not dim display when put next to the ear.
[bugreport(5)-a23nsxx-AP1A.240505.005.B1-2024-05-22-10-08-07.zip](https://github.com/MisterZtr/PixelOS_gsi/files/15400018/bugreport.5.-a23nsxx-AP1A.240505.005.B1-2024-05-22-10-08-07.zip)

**_Here are the tab a8 issues only_**
1: I can not seem to take a bug reports as the device restarts after a few seconds whenever i click full report or interactive report. 
[bug report.txt](https://github.com/MisterZtr/PixelOS_gsi/files/15441167/bug.report.txt)

2: The tablet brightness scroller does not work as any adjustment (in settings and in the drop down) does not work and reboots the System UI and sends me to the lockscreen.
[brightness logs.txt](https://github.com/MisterZtr/PixelOS_gsi/files/15441168/brightness.logs.txt)

3: I can not update wallpaper by choosing an image in (Google) gallery app or google photos, i have the image ready but when i click "use as"  and then click (gallery) wallpaper/(photos)wallpaper nothing happens.
[err 3.txt](https://github.com/MisterZtr/PixelOS_gsi/files/15441170/err.3.txt)

~~4: When choosing a wallpaper in the settings menu then head to choose from photos it stops working for some reason when i choose an image and even before i click set as wallpaper. Seems like an issue with the "wallpaper and styles app" implementation since it tells me that wallpaper and styles has stopped working.~~ Works Now For Some Reason But Here Are Logs, Failed Before 2 Times, Now Just Works.
[err4.txt](https://github.com/MisterZtr/PixelOS_gsi/files/15441236/err4.txt)

5: May i also suggest a feature to limit charging to like 80? lol just sliding this here :)

May i suggest testing the OS on a tab to have a feel of it and maybe get logs locally? Since some errors seem to be native to the tab alone so maybe it has to be due to the Android L implementation? LIke the brightness thing. It can help :) or maybe have me test them out and give me a way to give logs since dev option does not allow me to do so.

6: Audio sounds quiet as hell and i have to pump it to over 70 to get listenable audio. Tried another ROM and audio even at 30 percent is good and 50 is loud. [This is the ROM am talking about and brightness is perfect too](https://github.com/naz664/crDroid_gsi)

Note i have labelled the reports based on which point i have made. Example: point 4 has bugreport(4)....as its logs. I will look at the tab and note anything else since the OS is on there still. This was a quick test and i am open to test more. Otherwise alot of things work and am happy on the tablet.

**Comment by monsiu** [comment]
Build info: treble_arm64_bN-userdebug 14 AP1A.240505.005.B1 eng.andrew.20240512.080656 release-keys
Serial number: R58T41C0X2P

**Comment by monsiu** [comment]
_Update on more bugs on the OS to highlight (as seen on Galaxy Tab A8 gta8wifi)_ 

3: I can not update wallpaper by choosing an image in (Google) gallery app or google photos, i have the image ready but when i click "use as"  and then click (gallery) wallpaper/(photos)wallpaper nothing happens.

4: When choosing a wallpaper in the settings menu then head to choose from photos it stops working for some reason when i choose an image and even before i click set as wallpaper. Seems like an issue with the "wallpaper and styles app" implementation since it tells me that wallpaper and styles has stopped working.

5: May i also suggest a feature to limit charging to like 80? lol just sliding this here :)

May i suggest testing the OS on a tab to have a feel of it and maybe get logs locally? Since some errors seem to be native to the tab alone so maybe it has to be due to the Android L implementation? LIke the brightness thing. It can help :) or maybe have me test them out and give me a way to give logs since dev option does not allow me to do so.

**Comment by MisterZtr** [comment]
So many bugs that I don't have. After all, I don't have a Samsung device

**Comment by monsiu** [comment]
Yea its weird but i donno what else to add. There was a GSI (or 2, i swear i can not remember since the tab a8 has a very long process of flashing) that worked so i may try again and find out specifically which one works or maybe i may be misremembering. 

Got so tired of flashing and reflashing(phone and tab) that i forgot which worked and which didn't and on which device.

Maybe forwarding whatever(GSI) worked without the errors can have you collaborating with the dev? Otherwise the folks like PHH and AndyYan can help. I will get back to you on my finds. Hope it helps.

**Comment by monsiu** [comment]
tested [Derpfest](https://github.com/KoysX/treble_DerpFest_GSI/releases) and [Evo X](https://github.com/ahnet-69/treble_evo) from both of those devs. Here are my finds from both:

Google Copy apps and Data works
Brightness is perfect. No need to even adjust the phh settings
Wallpaper from settings works.
Plus Derp has a charging control feature :)

**_Some notes_**
Both Derp and Evo do not allow me to take bug reports...i can not see it in dev options. Could there be a reason?
Both do not allow me to set a wallpaper using google gallery(nothing happens when i try) but google photos works.
Your Pixel OS is best optimized for tablets. on the pixel OS its catered more so to tablets by staying in landscape orientation even in lock screen.

Maybe those devs can help? and maybe hit up phh husson https://github.com/phhusson 
I can test the fixes for you :) The OS is damn good and near perfection for the Tablets if you iron these its damn perfect!

**Comment by MisterZtr** [comment]
It is better to use logcat to get logs

**Comment by monsiu** [comment]
> It is better to use logcat to get logs

Done, used logcat extreme with magisk root for the logs for TAB A8 and compiled the errors in one list on the first comment.
Tell me how it looks. Each log is under the respective error and properly named.

**Comment by MisterZtr** [comment]
I can't fix bugs on individual devices. Contact users who are using this smartphone
