### ISSUE TITLE
zip END header not found

### ISSUE THREAD

**Issue by User8395** [MisterZtr/PixelOS_gsi#70]
At 80%, build fails with the error zip END header not found

![20240613_192709.jpg](https://github.com/MisterZtr/PixelOS_gsi/assets/49075348/08951635-9318-453a-b987-a4e51f89372c)

**Comment by MisterZtr** [comment]
That's already a problem with PixelOS source code

**Comment by User8395** [comment]
I tried again and it failed at 94%.

Are there any stable branches from their source?

**Comment by MisterZtr** [comment]
I had the same problem. gms folder is cloned corrupted during repo sync. Need to clone the repository yourself
```bash
rm -rf PixelOS/vendor/gms
git clone https://gitlab.com/PixelOS-Devices/vendor_gms.git PixelOS/vendor/gms
```
