### ISSUE TITLE
[Tecno Camon 20 Pro (CK7n)] The onscreen fingerprint does not work

### ISSUE THREAD

**Issue by nerlyw648** [MisterZtr/PixelOS_gsi#72]
When installing a fingerprint, the screen does not respond to the finger and there is no hint where to click.

**Comment by MisterZtr** [comment]
Is this problem present in aosp from Treble droid?

**Comment by nerlyw648** [comment]
> Is this problem present in aosp from Treble droid?

Yes, in that firmware this problem is repeated.

**Comment by MisterZtr** [comment]
Then sorry, I can't solve your problem
