### ISSUE TITLE
[Tecno Camon 20 Pro (CK7n)] Freezes when a notification pops up

### ISSUE THREAD

**Issue by nerlyw648** [MisterZtr/PixelOS_gsi#73]
When a pop-up notification arrives, the application that is currently open on the screen may freeze. The hangups disappear when the notification disappears from view.

**Comment by MisterZtr** [comment]
Yeah, I've noticed that, too

**Comment by nerlyw648** [comment]
> Yeah, I've noticed that, too

I think I've figured out what the problem is. This happens while playing music. If you close the application that is playing the sound (or stop playback), then everything works fine.

Correction: if you swipe the notification from the media player, the freezes disappear as well. (there is a suspicion that this is due to the cover of the song in the media player.) It was also noticed that if the media player is active in notifications, then there are microfreezes when opening the notification list.

**Comment by MisterZtr** [comment]
This is all fixed in the June qpr3 build
