### ISSUE TITLE
Lagging

### ISSUE THREAD

**Issue by TwinBurble** [MisterZtr/PixelOS_gsi#74]
Installed the GSI on my Galaxy A15 and it's laggy, i tried everything even forced fps to 90 butbnothing worked, please fix this issue

**Comment by MisterZtr** [comment]
It depends on your vendor. There are many modules for G99 that increase smoothness

**Comment by TwinBurble** [comment]
I re-installed the gsi and tried to remove the lag, I went to the treble
settings - Misc features and enabled GED KPI support and disabled SF GL
back pressure, rebooted the phone and it worked, now there's no lag.

Also I love this gsi, but there's another issue, I set up a face unlock but
whenever I try to unlock my phone it says "Face unlock unavailable" I tried
setting it again but still didn't work, but still I really love the gsi.
