### ISSUE TITLE
How do I remove no service on a blocked android device? I use a tablet.

### ISSUE THREAD

**Issue by kafaserver** [MisterZtr/PixelOS_gsi#75]

**Comment by MisterZtr** [comment]
I'm not quite sure what you mean. And it seems to be more of an android question rather than a PixelOS question

**Comment by jaimbo** [comment]
I think I know what they're talking about. I use a tablet with no Sim or mobile data capabilities and in this GSI I have things like "Emergency Calls Only" and  "No SIM" in various locations throughout the OS.

I think in previous versions I've used Phh Treble Settings>Misc features>Remove Telephony Subsystem - but this does not seem to work in the current version of PixelOS.

It looks like this option should run /system/bin/remove-telephony.sh - which contains:

```
#!/system/bin/sh

mount -o remount,rw /
mount -o remount,rw /system
remount

rm -Rf /system/priv-app/TeleService
mount -o remount,ro /
mount -o remount,ro /system
sync
reboot
```
