### ISSUE TITLE
Errors while syncing Repo

### ISSUE THREAD

**Issue by imbroglius** [MisterZtr/PixelOS_gsi#76]
Everytime I try to sync the Repo there are many errors like:

error: Cannot fetch platform/external/python/mako from https://android.googlesource.com/platform/external/python/mako

**Comment by MisterZtr** [comment]
Source synchronization is fine right now. Your dns server may be dropping requests to github because they are happening too often. To solve this problem, I use dnsmasq as a local cache for dns

**Comment by imbroglius** [comment]
It has been a problem under Ubuntu.

I installes Mint and everything runs fine without errors
