### ISSUE TITLE
No SMS recieving, No fingerprint S21FE (990E)

### ISSUE THREAD

**Issue by KadirJeager** [MisterZtr/PixelOS_gsi#77]
Hi thanks for all you did it was the best gsi ever used. SMS sometimes working but not all the time. Fingerprint is on the settings but no save. 
I have made my search and couldnt find any soulition. So backed to the stock rom by not desiring.

**Comment by MisterZtr** [comment]
I can't fix bugs on individual devices. Contact users who are using this smartphone
