### ISSUE TITLE
Phh IMS detects wrong Mediathek Vendor

### ISSUE THREAD

**Issue by imbroglius** [MisterZtr/PixelOS_gsi#78]
When I try to Install the correct IMS apk for my Redmi 13c phh treble settings shows me R+ instead of S Variant.

When I Install R+ Variant mobile Internet dies.

![Screenshot_20240702-110254.png](https://github.com/MisterZtr/PixelOS_gsi/assets/163344413/b935a9e1-4090-412c-91ec-82248ed2a1be)

S would be the correct Version to Install.

**Comment by MisterZtr** [comment]
In treble_app code, this version of ims was shown as intended for devices with u version. In the July update of the pixel, the s version will be installed
