### ISSUE TITLE
Galaxy Tab S7 Plus still can't enter home screen on latest version.

### ISSUE THREAD

**Issue by noahhhi** [MisterZtr/PixelOS_gsi#80]
There is a moment the home screen wallpaper appeared, then the tablet repeat playing the boot-animation. It is weird that moment I could use ADB commend. Here is the logcat.
[adb.log](https://github.com/user-attachments/files/16112134/adb.log)

**Comment by noahhhi** [comment]
DSU works on my tablet, I think it might need a factory reset to upgrade system.

**Comment by noahhhi** [comment]
Once I change the smallest width to 800 in developer options, the error occurred again.

**Comment by MisterZtr** [comment]
I can't fix bugs on individual devices. Contact users who are using this smartphone
