### ISSUE TITLE
HW buttons vibration not working

### ISSUE THREAD

**Issue by DocMAX** [MisterZtr/PixelOS_gsi#81]
I force enabled the nav bar but there is not vibration on press.
Phone is Unihertz Jelly Star.

**Comment by MisterZtr** [comment]
On blackview shark 8 vibration works

**Comment by DocMAX** [comment]
Yes, other devices work. Any idea where to look at? *.kl files?

**Comment by DocMAX** [comment]
Please please please if anyone is familar with the Android OS, please tell me where is the config file for hard ware button configuration and vibration. THANK YOU!!!
