### ISSUE TITLE
Face Unlock&System_server High CPU usage

### ISSUE THREAD

**Issue by notempko** [MisterZtr/PixelOS_gsi#88]
Hi there
I am a PixelOS GSI User
I come from China so that my English skill might be bad,Please forgive me🥺
My machine:
OnePlus Ace2V(The same as OnePlus Nord3 5G) run with PixelOS GSI(Not slim version &vndklite version)
There is two problems on it
First
The face unlock works normally on PixelOS 14 February release(March 2)
But when I run the versions which are higher that this version,the face unlock can't record the face at all(Such as May release&May release)
I don't know how to help you to get the log to solve the problem,I can only think that face unlock can run normally on old face unlock app(Paranoid Sense?)
Second
When the time 20:00 to 00:00(8:00pm to 12:00am),The Linux process System_server will take a lot CPU resource
If I change the time myself,The process will be normal
So this process must have the relation to the time
Can you tell me how to Capture log about this process,I will send the log soon
Thanks!

**Comment by zmz125000** [comment]
same on july build. have you found a solution yet?

**Comment by zmz125000** [comment]
fixed by using phh misc remove telephony subsystem (for pad)
