### ISSUE TITLE
Boot Animation

### ISSUE THREAD

**Issue by thefatos** [MisterZtr/PixelOS_gsi#90]
the bootanimation linked doesn't work on devices with smaller screens, my a21s which has a 1600x720 screen has the boot animation in the corner

**Comment by MisterZtr** [comment]
I have a smartphone with same screen resolution, and default bootanimation looks fine there

**Comment by thefatos** [comment]
> I have a smartphone with same screen resolution, and default bootanimation looks fine there

i wonder, what bootanimation did you flash, the 1080p one or the 1440p, since this is weird if the same resolution produces 2 outcomes

**Comment by MisterZtr** [comment]
No flashing needed, bootanimation have defaults resolution 720p

**Comment by thefatos** [comment]
> No flashing needed, bootanimation have defaults resolution 720p

in the new update or the default pixelOS gsi one?

**Comment by thefatos** [comment]
> > No flashing needed, bootanimation have defaults resolution 720p
> 
> in the new update or the default pixelOS gsi one?

im talking about the one in the release page with the material you colors

**Comment by MisterZtr** [comment]
> > No flashing needed, bootanimation have defaults resolution 720p
> 
> in the new update or the default pixelOS gsi one?

It's bootanimation's resolution since January

**Comment by thefatos** [comment]
> > > No flashing needed, bootanimation have defaults resolution 720p
> > 
> > 
> > in the new update or the default pixelOS gsi one?
> 
> It's bootanimation's resolution since January

oh okay, i guess ill have to use the normal bootanimation instead of the bootanimation_1080.zip
