### ISSUE TITLE
Security vulnerability through adb !!!

### ISSUE THREAD

**Issue by rexackermann** [MisterZtr/PixelOS_gsi#97]
adb does not do any authorization whatsoever
It allows every device to use adb

As a result -->  /if device is in wrong hands private data can easily be pulled if adb is enabled 
which shan't be the case.

I await your reply

Thank you for maintaining such a great project.

**Comment by rexackermann** [comment]
Temporary fix:

use a build.prop editor and change the value of ro.adb.secure to 1 from 0

**Comment by MisterZtr** [comment]
Just turn adb off in developer settings. Automatic adb authentication is necessary for debugging when the build hangs on bootanimation
